# Axisym Punch-Through Shear Test

This example couples two domains via an zero-thickness interface. 

State - 2021-07-19 [RC]:

- Slide34 included with not verified material parameters. The push through test is running for a small step size
- Add the force control boundary conditions in analogy to single facet example
- Change of the parameters to brittle response leads to convergence problems at the transition to inelastic state - check the range which converges.
- Either initial or secant stiffness has been used     

In [1]:
%matplotlib widget
# import time
# from bmcs_expsim.utils.mlab_decorators import decorate_figure
from mayavi import mlab
import numpy as np
np.seterr(divide='ignore', invalid='ignore') 
import warnings
import matplotlib.pylab as plt

ImportError: DLL load failed while importing vtkRenderingCore: The specified procedure could not be found.

In [2]:
from ibvpy.api import TStepBC , TFCyclicNonsymmetricConstant, TFBilinear
from ibvpy.bcond import BCSlice, BCDof
from ibvpy.xmodel.xdomain_fe_grid_axisym import XDomainFEGridAxiSym
from ibvpy.xmodel.xdomain_interface import XDomainFEInterface

In [3]:
from ibvpy.fets import FETS2D4Q
from ibvpy.fets.fets1D5 import FETS1D52ULRH

In [4]:
from ibvpy.tmodel.viz3d_scalar_field import \
    Vis3DStateField, Viz3DScalarField
from ibvpy.tmodel.viz3d_tensor_field import \
    Vis3DTensorField, Viz3DTensorField

# Material models

In [5]:
from bmcs_matmod.slide.vslide_34_TN_axisym import Slide34
from ibvpy.tmodel.mats3D.mats3D_elastic.vmats3D_elastic import \
    MATS3DElastic
from bmcs_matmod.slide.slide_explorer import SlideExplorer

# FE discretization - Displacement-controlled

In [38]:
n_x_e = 3
n_inner_y_e = 2
n_outer_y_e = 2
n_steel_y_e = 2
L_x = 40.0
R_in = 25.0
R_out = 50.0
R_steel = R_out + 7

xd_lower = XDomainFEGridAxiSym(coord_min=(0, 0),
                          coord_max=(L_x, R_in),
                          shape=(n_x_e, n_inner_y_e),
                          integ_factor=2 * np.pi,
                          fets=FETS2D4Q())
xd_upper = XDomainFEGridAxiSym(coord_min=(0, R_in),
                          coord_max=(L_x, R_out),
                          shape=(n_x_e, n_outer_y_e),
                          integ_factor=2 * np.pi,
                          fets=FETS2D4Q())
xd_ring = XDomainFEGridAxiSym(coord_min=(0, R_out),
                          coord_max=(L_x, R_steel),
                          shape=(n_x_e, n_steel_y_e),
                          integ_factor=2 * np.pi,
                          fets=FETS2D4Q())

m1 = MATS3DElastic(E=37000, nu=0.18)
m2 = MATS3DElastic(E=37000, nu=0.18)
m3 = MATS3DElastic(E=210000, nu=0.3)

xd12 = XDomainFEInterface(
#     I=xd_lower.mesh.I[1:-1,-1],
#     J=xd_upper.mesh.I[1:-1, 0],
    I=xd_lower.mesh.I[-1, -1:-1],
    J=xd_upper.mesh.I[0, 1:-1],
    fets=FETS1D52ULRH()
)

xd23 = XDomainFEInterface(
    I=xd_lower.mesh.I[-1,:],
    J=xd_ring.mesh.I[0,:,0],
#     I=xd_lower.mesh.I[1:-1, -1],
#     J=xd_upper.mesh.I[1:-1, 0],
    fets=FETS1D52ULRH()
)

In [22]:
#bond_m = Slide34(E_T=10000, E_N=10000)
material_params =  dict(
     E_T=350, gamma_T=650, K_T=100, S_T=0.75, c_T=2, bartau=3000, 
     E_N=370, S_N=0.0005, c_N = 3, m = 0.0, f_t=3000, f_c=100000, f_c0 = 75000, eta=0. , r =12)
bond_m = Slide34(**material_params)

material_params_2 =  dict(
     E_T=350, gamma_T=650, K_T=100, S_T=0.75, c_T=2, bartau=3000, 
     E_N=2000, S_N=0.000005, c_N = 3, m = 0.0, f_t=10000, f_c=10000, f_c0 = 7500, eta=0. , r =12)
bond_m_2 = Slide34(**material_params_2)

In [23]:
se1 = SlideExplorer(n_steps=500, k_max=50)
se1.slide_model.trait_set(**material_params_2)
se1.trait_set(s_x_1 = 0.5, s_y_1 = 0, w_1 =0);
se1.run()

In [22]:
se1.interact()

In [39]:
axisym = BCSlice(slice=xd_lower.mesh[0, :, 0, :],
                 var='u', dims=[1], value=0)
outer_ring_hoop = BCSlice(slice=xd_upper.mesh[-1, :, -1, :],
                 var='u', dims=[1], value=0.0)
fixed_upper_support = BCSlice(slice=xd_upper.mesh[:, -1, :, -1],
                 var='u', dims=[0], value=0)
fixed_ring_support = BCSlice(slice=xd_ring.mesh[:, -1, :, -1],
                 var='u', dims=[0], value=0)
loaded_lower= BCSlice(slice=xd_lower.mesh[:, 0, :, 0],
                  var='u', dims=[0], value=-0.1)
unloaded_inner = BCSlice(slice=xd_lower.mesh[0, :, 0, :],
                  var='u', dims=[0], value=0)
bc1 = [axisym, fixed_upper_support, loaded_lower]

In [40]:
print(xd_lower.mesh[:,:,:,:].dofs)
xd12.mesh.dofs

[[[ 0  1]
  [ 6  7]
  [ 8  9]
  [ 2  3]]

 [[ 2  3]
  [ 8  9]
  [10 11]
  [ 4  5]]

 [[ 6  7]
  [12 13]
  [14 15]
  [ 8  9]]

 [[ 8  9]
  [14 15]
  [16 17]
  [10 11]]

 [[12 13]
  [18 19]
  [20 21]
  [14 15]]

 [[14 15]
  [20 21]
  [22 23]
  [16 17]]]


array([[ 0,  1],
       [ 2,  3],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1]])

In [13]:
m = TStepBC(
    domains=[(xd_lower, m1),
             (xd_upper, m2),
             (xd12, bond_m),
#              (xd23, bond_m_2),
#              (xd_ring, m3),
             ],
    bc=bc1,  # + bc2,
)

m.hist.vis_record = {
#    'strain': Vis3DTensorField(var='eps_ab'),
    'stress': Vis3DTensorField(var='sig_ab'),
    #        'kinematic hardening': Vis3DStateField(var='z_a')
}

s = m.sim
s.tloop.verbose = True
s.tloop.k_max = 1000
s.tline.step = 0.1
s.tstep.fe_domain.serialized_subdomains

In [14]:
#bond_m.interact()

In [15]:
xd12.hidden = True
xd23.hidden = True
s.reset()
s.run()

t:	 0.00(0), 
	 0.10

RuntimeError: Factor is exactly singular

# Plot the punch-through curve

In [ ]:
F_to = m.hist.F_t
U_to = m.hist.U_t

In [ ]:
F_to.shape

In [ ]:
F_outer_t = np.sum(F_to[:, fixed_upper_support.dofs], axis=-1)
F_inner_t = np.sum(F_to[:, loaded_lower.dofs], axis=-1)
U_inner_right_t = np.average(U_to[:, loaded_lower.dofs], axis=-1)
U_inner_left_t = np.average(U_to[:, unloaded_inner.dofs], axis=-1)
#U_inner_bot_t = np.average(U_to[:, free_inner_y.dofs], axis=-1)

In [ ]:
_, ax = plt.subplots(1,1)
ax.plot(-U_inner_right_t, F_outer_t, label='F_outer(U_top)')
ax.plot(-U_inner_left_t, F_outer_t, label='F_outer(U_top)')
ax.plot(-U_inner_right_t, F_inner_t, label='F_inner(U_top)')
#ax.plot(-U_inner_bot_t, F_inner_t, label='F_inner(U_bot)')
ax.legend()

In [ ]:
if True:
    mlab.options.backend = 'envisage'
    mlab.options.offscreen = False # 'envisage'
    f_strain = mlab.figure()
    scene = mlab.get_engine().scenes[-1]
    scene.name = 'stress'
    strain_viz = Viz3DTensorField(vis3d=m.hist['stress'])
    strain_viz.setup()
    strain_viz.warp_vector.filter.scale_factor = 0.1
    strain_viz.plot(s.tstep.t_n)
    mlab.show()

In [ ]:
states_t = [states_t[2] for states_t in m.hist.state_vars]
var_names = states_t[0].keys()
EpsSig_t = {
    var_name: np.array([ state_dict[var_name] for state_dict in states_t ]) 
    for var_name in var_names 
}

In [ ]:
var_names

In [ ]:
u_pi_N = EpsSig_t['w_pi']
u_pi_Tx = EpsSig_t['s_pi_x']
sig_pi_N = EpsSig_t['sig_pi']
sig_pi_Tx = EpsSig_t['tau_pi_x']
sig_pi_Ty = EpsSig_t['tau_pi_y']
omega_Nx = EpsSig_t['omega_N']
omega_Tx = EpsSig_t['omega_T']

In [ ]:
x_m = xd12.x_Eia[:,:,0].flatten()

In [ ]:
_, (ax, ax_omega) = plt.subplots(1,2, figsize=(10,5))
idx = -1
ax_u = ax.twinx()
ax.plot(x_m, sig_pi_N[idx,:,:].flatten(), color='blue', label='sig')
ax_u.plot(x_m, u_pi_N[idx,:,:].flatten(), color='blue', linestyle='dashed', label='sig')
ax.plot(x_m, sig_pi_Tx[idx,:,:].flatten(), 'o-', color='red', label='tau')
#ax.fill_between(x_m.flatten().flatten(), sig_pi_Tx[idx,:,:].flatten(), 0, 'o-', color='red', alpha=0.2)
ax_u.plot(x_m, u_pi_Tx[idx,:,:].flatten(), color='red', linestyle='dashed', label='u_Tx')
ax_omega.plot(x_m, omega_Nx[idx,:,:].flatten(), color='green', label='omega_N')
ax_omega.plot(x_m, omega_Tx[idx,:,:].flatten(), color='green', linestyle='dashed', label='omega_T')
ax.legend()
ax_omega.legend()

In [ ]:
sig_pi_Tx.shape

In [ ]:
_, (ax, ax_omega) = plt.subplots(1,2, figsize=(10,5))
idx = -1
ax_u = ax.twinx()

ax.plot(-U_inner_right_t, sig_pi_Tx[:,0,0].flatten(), color='red', label='tau')


ax_omega.plot(-U_inner_right_t, omega_Tx[:,0,0].flatten(), color='green', linestyle='dashed', label='omega_T')
ax.legend()
ax_omega.legend()

In [ ]:
max(sig_pi_Tx[:,0,0])

# FE discretization - Force-controlled

In [ ]:
n_y_e = 10
n_inner_x_e = 5
n_outer_x_e = 5
L_x = 200.0
R_in = 100.0
R_out = 200.0
xd_lower = XDomainFEGridAxiSym(coord_min=(0, 0),
                          coord_max=(L_x, R_in),
                          shape=(n_y_e, n_inner_x_e),
                          integ_factor=2 * np.pi,
                          fets=FETS2D4Q())
xd_upper = XDomainFEGridAxiSym(coord_min=(0, R_in),
                          coord_max=(L_x, R_out),
                          shape=(n_y_e, n_outer_x_e),
                          integ_factor=2 * np.pi,
                          fets=FETS2D4Q())
m1 = MATS3DElastic(E=28000, nu=0.3)
m2 = MATS3DElastic(E=28000, nu=0.3)

xd12 = XDomainFEInterface(
    I=xd_lower.mesh.I[1:-1, -1],
    J=xd_upper.mesh.I[1:-1, 0],
    fets=FETS1D52ULRH()
)

In [ ]:
#bond_m = Slide34(E_T=10000, E_N=10000)
material_params = dict(
         E_T=100, gamma_T=200, K_T=0, S_T=0.05, c_T=3, bartau=3, 
         E_N=100, S_N=0.05, c_N = 3, m = 0.15, f_t=5, f_c=80, f_c0 = 40, eta=0.2)
bond_m = Slide34(**material_params)

In [ ]:
tf_force = TFBilinear()
tf_force.interact()

In [ ]:
axisym = BCSlice(slice=xd_lower.mesh[0, 0, 0, 0],
                 var='u', dims=[1], value=0)
fixed_upper_support = BCSlice(slice=xd_upper.mesh[0, :, 0, :],
                 var='u', dims=[0], value=0)
loaded_lower_slice= BCSlice(slice=xd_lower.mesh[-1, :, -1, :],
                  var='u', dims=[0], value=0.5)
loaded_lower_dofs = loaded_lower_slice.dofs

load = 500
F = load / len(loaded_lower_dofs)

loaded_lower = [BCDof(var='f', dof=dof, value = F, time_function=tf_force  ) 
                     for dof in loaded_lower_dofs]

bc1 = [axisym, fixed_upper_support, loaded_lower]

In [ ]:
m = TStepBC(
    domains=[(xd_lower, m1),
             (xd_upper, m2),
             (xd12, bond_m),
             ],
    bc=bc1,  # + bc2,
)

m.hist.vis_record = {
    'strain': Vis3DTensorField(var='eps_ab'),
    #        'damage': Vis3DStateField(var='omega_a'),
    #        'kinematic hardening': Vis3DStateField(var='z_a')
}

s = m.sim
s.tloop.verbose = True
s.tloop.k_max = 1000
s.tline.step = 0.02
s.tstep.fe_domain.serialized_subdomains

In [ ]:
#bond_m.interact()

In [ ]:
xd12.hidden = True
s.reset()
s.run()